const page = location.pathname.split('/').pop() || 'index.html';
const routes = [['index.html','Início'],['estudio.html','Estúdio'],['movimento.html','Movimento'],['resultados.html','Resultados'],['experimentos.html','Experimentos'],['ambiente.html','Ambiente']];
const esc = value => String(value ?? '—').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const app = document.createElement('div'); document.body.append(app);
app.innerHTML = `<header><strong>MOVA</strong><nav>${routes.map(([url,label])=>`<a class="${page===url?'active':''}" href="${url}">${label}</a>`).join('')}</nav></header><main id="view"><p>Carregando sistema…</p></main>`;
const view = document.querySelector('#view');
async function api(url, options){const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw Error(data.error||`HTTP ${r.status}`);return data;}
function fail(e){view.innerHTML=`<div class="card error"><h2>Não foi possível conectar ao MOVA</h2><p>${esc(e.message)}</p><p>Inicie com <code>.venv/Scripts/python web/server.py</code> e abra <code>http://127.0.0.1:8000</code>.</p></div>`;}
function deviceCard(d){const m=d.memory||{};return `<div class="card"><h2>${esc(d.name)}</h2><p>${esc(d.id)} · ${esc(d.backend)}</p><p>Memória: ${esc(m.free_gb)} GB livres / ${esc(m.total_gb)} GB</p><p>Precisões: fp32${d.fp16?', fp16':''}${d.bf16?', bf16':''}</p></div>`;}
async function ambiente(){const x=await api('/api/info');view.innerHTML=`<h1>Ambiente</h1><p class="muted">Leitura atual de <code>core.info</code> nesta máquina.</p><div class="grid">${x.devices.map(deviceCard).join('')}</div><div class="card"><h2>Sistema</h2><p>Python ${esc(x.python)} · PyTorch ${esc(x.pytorch)} · MOVA ${esc(x.mova)}</p><p>Disco livre: ${esc(x.disk_free_gb)} GB</p><p>${esc(x.os)}</p></div><h2>Modelos registrados</h2><div class="grid">${Object.entries(x.model_details).map(([alias,m])=>`<div class="card"><h2>${esc(m.spec.name)}</h2><p>${esc(m.spec.description)}</p><p>Alias: ${esc(alias)} · pesos: ${esc(m.spec.weights||'nenhum')}</p><p>Dependências ausentes: ${esc(m.missing_requirements.join(', ')||'nenhuma')}</p><p>Compatibilidade:</p>${m.compatibility.map(c=>`<p><span class="badge">${esc(c.status)}</span> ${esc(c.runtime)} / ${esc(c.device)} — ${esc(c.detail)}</p>`).join('')}</div>`).join('')}</div>`;}
let allRuns=[], selected=null, filter='all';
function resultLink(r){return r.media?.['output.mp4']?`<a class="button" href="resultados.html?run=${encodeURIComponent(r.run_id)}">Ver vídeo</a>`:'';}
function renderRuns(){const shown=allRuns.filter(r=>filter==='all'||r.kind===filter);const r=allRuns.find(x=>x.run_id===selected)||shown[0];view.innerHTML=`<h1>Experimentos</h1><p class="muted">Registros locais de <code>experiments/runs</code>. Atualize a página para ler novos runs.</p><div class="row">${['all','extract','baseline','train'].map(k=>`<button data-filter="${k}" style="opacity:${filter===k?1:.5}">${k==='all'?'Todos':k}</button>`).join('')}</div><div class="card" style="overflow:auto"><table><thead><tr><th>Run</th><th>Tipo</th><th>Modelo</th><th>Status</th><th>Tempo</th></tr></thead><tbody>${shown.map(v=>`<tr data-id="${esc(v.run_id)}"><td>${esc(v.run_id)}</td><td>${esc(v.kind)}</td><td>${esc(v.model)}</td><td>${esc(v.status)}</td><td>${esc(v.wall_time_s)} s</td></tr>`).join('')}</tbody></table>${shown.length?'':'<p>Nenhum registro encontrado.</p>'}</div>${r?`<div class="card"><h2>${esc(r.run_id)}</h2><p>Status: ${esc(r.status)} · ${esc(r.kind)}</p><p>Início: ${esc(r.started_at)}</p><p>Artefatos: ${esc(r.artifacts_dir)}</p><p>Erro: ${esc(r.error||'nenhum')}</p><div class="row"><a class="button" target="_blank" href="${esc(r.record_url)}">Abrir run.json</a>${resultLink(r)}</div><details><summary>Registro completo</summary><pre>${esc(JSON.stringify(r,null,2))}</pre></details></div>`:''}`;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderRuns()});document.querySelectorAll('tr[data-id]').forEach(tr=>tr.onclick=()=>{selected=tr.dataset.id;renderRuns()});}
async function experimentos(){allRuns=await api('/api/runs');renderRuns();}
async function resultados(){const runs=await api('/api/runs');const id=new URLSearchParams(location.search).get('run');const valid=runs.filter(r=>r.media?.['output.mp4']);const chosen=valid.find(r=>r.run_id===id)||valid[0];view.innerHTML=`<h1>Resultados</h1><p class="muted">Saídas reais registradas pelo MOVA.</p>${chosen?`<div class="card"><h2>${esc(chosen.run_id)}</h2><video controls src="${esc(chosen.media['output.mp4'])}"></video><p>Modelo: ${esc(chosen.model)} · status: ${esc(chosen.status)}</p><a href="${esc(chosen.record_url)}" target="_blank">Abrir registro</a></div>`:'<div class="card">Ainda não há vídeo gerado. Execute uma inferência no Estúdio.</div>'}<div class="card"><h2>Outras saídas</h2>${valid.map(r=>`<p><a href="resultados.html?run=${encodeURIComponent(r.run_id)}">${esc(r.run_id)}</a></p>`).join('')||'Nenhuma'}</div>`;}
async function encodeFile(file){return {name:file.name,data:await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);})};}
async function submit(operation){const ref=document.querySelector('#reference')?.files[0],motion=document.querySelector('#motion')?.files[0];if(!motion||(operation==='infer'&&!ref)){document.querySelector('#job').textContent='Selecione os arquivos necessários.';return;}const data={operation,motion:await encodeFile(motion)};if(ref)data.reference=await encodeFile(ref);if(operation==='infer'){data.model=document.querySelector('#model').value;data.frames=Number(document.querySelector('#frames').value);data.steps=Number(document.querySelector('#steps').value);}document.querySelector('#submit').disabled=true;try{const job=await api('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});poll(job.id);}catch(e){document.querySelector('#job').textContent=e.message;document.querySelector('#submit').disabled=false;}}
async function poll(id){const el=document.querySelector('#job');if(!el)return;try{const j=await api('/api/jobs/'+id);el.innerHTML=`<p>Status: ${esc(j.status)}</p>${j.error?`<p class="error">${esc(j.error)}</p>`:''}<pre>${esc((j.log||[]).join('\n'))}</pre>${j.output?`<video controls src="${esc(j.output)}"></video>`:''}${j.run_id?`<p><a href="experimentos.html">Ver run ${esc(j.run_id)}</a></p>`:''}`;if(j.status==='running')setTimeout(()=>poll(id),1500);else document.querySelector('#submit').disabled=false;}catch(e){el.textContent=e.message;}}
function estudio(){view.innerHTML=`<h1>Estúdio</h1><p class="muted">Inferência real via <code>core.inference.run_inference</code>. O modelo tiny gera ruído e valida o pipeline; Wan usa pesos locais e nunca inicia download pela interface.</p><div class="card"><label>Imagem de referência</label><input id="reference" type="file" accept="image/png,image/jpeg,image/webp"><label>Vídeo de movimento</label><input id="motion" type="file" accept="video/mp4,video/quicktime,video/webm"><div class="row"><div><label>Modelo</label><select id="model"><option value="tiny">tiny · teste</option><option value="wan">Wan 1.3B · pesos locais</option></select></div><div><label>Quadros (4k+1)</label><select id="frames"><option>5</option><option>9</option><option selected>17</option><option>33</option></select></div><div><label>Passos</label><input id="steps" type="number" min="1" max="50" value="2"></div></div><p><button id="submit">Gerar</button></p><div id="job" aria-live="polite"></div></div>`;document.querySelector('#model').onchange=e=>{document.querySelector('#frames').value=e.target.value==='tiny'?'5':'17';document.querySelector('#steps').value=e.target.value==='tiny'?'2':'30'};document.querySelector('#submit').onclick=()=>submit('infer');}
function movimento(){view.innerHTML=`<h1>Movimento</h1><p class="muted">Extração real de corpo, rosto e mãos com MediaPipe, registrada em experiments/runs.</p><div class="card"><label>Vídeo de movimento</label><input id="motion" type="file" accept="video/mp4,video/quicktime,video/webm"><p><button id="submit">Extrair movimento</button></p><div id="job" aria-live="polite"></div></div>`;document.querySelector('#submit').onclick=()=>submit('preprocess');}
function inicio(){view.innerHTML=`<h1>MOVA</h1><p class="muted">Motion control local: referência + vídeo de movimento → vídeo gerado.</p><div class="grid"><div class="card"><h2>Estúdio</h2><p>Envie arquivos e execute o pipeline real.</p><a class="button" href="estudio.html">Abrir Estúdio</a></div><div class="card"><h2>Movimento</h2><p>Extraia pose, rosto e mãos de um vídeo.</p><a class="button" href="movimento.html">Abrir Movimento</a></div><div class="card"><h2>Experimentos</h2><p>Inspecione os registros locais.</p><a class="button" href="experimentos.html">Ver runs</a></div></div>`;}
({ 'index.html':inicio,'estudio.html':estudio,'movimento.html':movimento,'resultados.html':resultados,'experimentos.html':experimentos,'ambiente.html':ambiente }[page]||inicio)()?.catch?.(fail);
